### ISSUE TITLE
Missing Icons links

### ISSUE THREAD

**Issue by AnshumanDhiman** [EOS-uiux-Solutions/eos-icons-landing#65]
Current State : 
Some of the eos-icons are not downloading, they are throwing the 404 error page not found as shown.

https://user-images.githubusercontent.com/67755381/155559692-5c0bd285-865d-4590-840c-3e9595de4d63.mp4

Expected State : 
The error must be resolved and the link should be updated.

**Comment by StarTrooper08** [comment]
Yes, the issue persists still, when I try to download icons I'm unable to do so!

**Comment by cyntss** [comment]
The issue is the following:

The eos-icons package that lives in Gitlab is maintained by SUSE. It seems they have removed some icons from their repository. But there is a fix for it.

If you try to download the icon from the option on "Edit icon" and then "SVG" or "PNG", you will see that it works. This is because the edit is using our API, and this should be always the case! For some reason, it seems we never updated the "Download" to consume the API directly.

@AnshumanDhiman or @StarTrooper08 , if any of you can work on this, let me know. This would be a very high-priority issue.

**Comment by cyntss** [comment]
@iifawzi  created the API so he would be a good point of contact in case you need anything.

More information about the API on this project:
https://github.com/EOS-uiux-Solutions/eos-icons-api
(it has postman tests available for you to see all routes available)

**Comment by AnshumanDhiman** [comment]
I can work on this issue
